//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="client.pingInter")]
    public interface pingInter
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pingInter/say", ReplyAction="http://tempuri.org/pingInter/sayResponse")]
        string say(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pingInter/say", ReplyAction="http://tempuri.org/pingInter/sayResponse")]
        System.Threading.Tasks.Task<string> sayAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface pingInterChannel : client.pingInter, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class pingInterClient : System.ServiceModel.ClientBase<client.pingInter>, client.pingInter
    {
        
        public pingInterClient()
        {
        }
        
        public pingInterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public pingInterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public pingInterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public pingInterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string say(string data)
        {
            return base.Channel.say(data);
        }
        
        public System.Threading.Tasks.Task<string> sayAsync(string data)
        {
            return base.Channel.sayAsync(data);
        }
    }
}
